# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Convert-Bencode_XS
version:      0.03
version_from: lib/Convert/Bencode_XS.pm
installdirs:  site
requires:
    perl: 5.6.0

build_requires:
    Test::More:                    0
    Storable:                      0

license: perl
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
